version: '3.7'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - {{ disk_db_dir }}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD={{ wordpress_db_password }}
    networks:
      private:
        ipv4_address: 10.6.0.3

  wordpress:
    image: wordpress:5
    container_name: wordpress
    restart: unless-stopped
    logging:
      driver: none
    volumes:
      - {{ disk_content_dir }}:/var/www/html
    depends_on:
      - mariadb
    environment:
      - VIRTUAL_HOST={{ extra_virtual_hosts|join(',') }}{{ ',' if extra_virtual_hosts else '' }}{{ virtual_host }}
      - WORDPRESS_DB_HOST=10.6.0.3
      - WORDPRESS_DB_PASSWORD={{ wordpress_db_password }}
    networks:
      private:
        ipv4_address: 10.6.0.4

  listmonk_db:
    image: postgres:14
    container_name: listmonk_db
    environment:
      - POSTGRES_PASSWORD={{ listmonk_db_password }}
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U listmonk']
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - {{ disk_listmonk_db_dir }}/pg:/var/lib/postgresql/data
    networks:
      private:
        ipv4_address: 10.6.0.5

  listmonk:
    image: listmonk/listmonk
    container_name: listmonk
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
    depends_on:
      - listmonk_db
    volumes:
      - /config/listmonk.toml:/listmonk/config.toml
    networks:
      private:
        ipv4_address: 10.6.0.6

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    network_mode: host
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=90d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - /config/prometheus:/etc/prometheus
      - /prometheus:/prometheus

networks:
  private:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
