- name: restart smartmouse-web
  systemd:
    name: smartmouse-web
    state: restarted

- name: reload nginx
  systemd:
    name: nginx.service
    state: reloaded

- name: enable letsencrypt gencerts
  systemd:
    name: gencerts.service
    daemon_reload: yes
    enabled: yes

- name: enable letsencrypt gencerts timer
  systemd:
    name: gencerts.timer
    daemon_reload: yes
    state: started
    enabled: yes
