[project]
name = "wp-plugin-info"
version = "0.1.0"
description = ""
authors = [
    { name = "Lucas", email = "lucas@smartmousetravel.com" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.3",
]

[project.scripts]
wp_plugin_info = "wp_plugin_info:main"

[dependency-groups]
dev = [
    "black",
    "isort",
    "mypy",
]
typing = [
    "types-requests>=2.32.0.20250306"
]

[tool.black]
line-length = 98
quiet = true

[tool.mypy]
strict = true
