global:
  scrape_interval:     30s
  evaluation_interval: 30s
  scrape_timeout:      5s

  external_labels:
    # TODO: Factor out this label
    monitor: 'www-prod-1'

rule_files:
  - 'node.rules'

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
          - '127.0.0.1:9100'
        labels:
          host: 'www-prod-1'
